// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamIntelligenceHub.Infrastructure.Persistence;

#nullable disable

namespace TeamIntelligenceHub.Infrastructure.Migrations
{
    [DbContext(typeof(TeamIntelligenceHubDbContext))]
    [Migration("20260820071922_AddActivity")]
    partial class AddActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AutoCreateTaskEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InitiativeId", "CreatedAt");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ActivityMention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MentionedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("ActivityId", "MentionedUserId")
                        .IsUnique();

                    b.ToTable("ActivityMentions", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessArea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExecutiveSponsorUserId")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiativeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SuccessMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("TargetEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutiveSponsorUserId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Initiatives", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Allocation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponsibilityArea")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InitiativeId", "UserId")
                        .IsUnique();

                    b.ToTable("InitiativeMembers", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SourceActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("SourceActivityId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComments", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique();

                    b.HasIndex("TaskCommentId");

                    b.ToTable("TaskCommentAttachments", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentMention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MentionedUserId")
                        .HasColumnType("int");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("TaskCommentId", "MentionedUserId")
                        .IsUnique();

                    b.ToTable("TaskCommentMentions", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Activity", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Activities")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ActivityMention", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Activity", "Activity")
                        .WithMany("Mentions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "MentionedUser")
                        .WithMany("ActivityMentions")
                        .HasForeignKey("MentionedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("MentionedUser");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Initiative", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "ExecutiveSponsor")
                        .WithMany("SponsoredInitiatives")
                        .HasForeignKey("ExecutiveSponsorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "Owner")
                        .WithMany("OwnedInitiatives")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExecutiveSponsor");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeMember", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Members")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("InitiativeMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeTask", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Tasks")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Activity", "SourceActivity")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("SourceActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Initiative");

                    b.Navigation("SourceActivity");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.TaskComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.InitiativeTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("TaskComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentAttachment", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.TaskComment", "TaskComment")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentMention", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "MentionedUser")
                        .WithMany("TaskCommentMentions")
                        .HasForeignKey("MentionedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.TaskComment", "TaskComment")
                        .WithMany("Mentions")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentionedUser");

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Activity", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskComment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Mentions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivityMentions");

                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");

                    b.Navigation("InitiativeMemberships");

                    b.Navigation("OwnedInitiatives");

                    b.Navigation("SponsoredInitiatives");

                    b.Navigation("TaskCommentMentions");

                    b.Navigation("TaskComments");
                });
#pragma warning restore 612, 618
        }
    }
}
