// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamIntelligenceHub.Infrastructure.Persistence;

#nullable disable

namespace TeamIntelligenceHub.Infrastructure.Migrations
{
    [DbContext(typeof(TeamIntelligenceHubDbContext))]
    partial class TeamIntelligenceHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AutoCreateTaskEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InitiativeId", "CreatedAt");

                    b.ToTable("Activity", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ActivityMention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MentionedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("ActivityId", "MentionedUserId")
                        .IsUnique();

                    b.ToTable("ActivityMentions", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Contribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("KeyTakeaway")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.PrimitiveCollection<string>("ReuseTargets")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("Types")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("InitiativeId", "CreatedAt");

                    b.ToTable("Contributions", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionAiPractice", b =>
                {
                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("TimeSavedHoursPerWeek")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Tool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UseCase")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("ContributionId");

                    b.ToTable("ContributionAiPractices", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.ToTable("ContributionAttachments", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("ResponsibilityArea")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ContributionId", "UserId")
                        .IsUnique();

                    b.ToTable("ContributionContributors", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionCustomerStory", b =>
                {
                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Quote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("ContributionId");

                    b.ToTable("ContributionCustomerStories", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ContributionId");

                    b.ToTable("ContributionLinks", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionMetric", b =>
                {
                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PreviousValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ReportingPeriod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContributionId");

                    b.ToTable("ContributionMetrics", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionRisk", b =>
                {
                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessImpact")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Mitigation")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupportNeeded")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("TargetResolutionDate")
                        .HasColumnType("date");

                    b.HasKey("ContributionId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Severity");

                    b.ToTable("ContributionRisks", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionTestimonial", b =>
                {
                    b.Property<int>("ContributionId")
                        .HasColumnType("int");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpeakerRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ContributionId");

                    b.ToTable("ContributionTestimonials", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.DocumentTestimonialAndCustomerStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audience")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ContributionAttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Quote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SpeakerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SpeakerRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContributionAttachmentId");

                    b.ToTable("DocumentTestimonialsAndCustomerStories", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangeImpact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExecutiveSponsorUserId")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedOutcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.PrimitiveCollection<string>("ImpactedRoles")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InitiativeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KeyObjective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifecycleStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SuccessMeasures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("TargetEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExecutiveSponsorUserId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Initiatives", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Allocation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponsibilityArea")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("InitiativeId", "UserId")
                        .IsUnique();

                    b.ToTable("InitiativeMembers", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SourceActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("SourceActivityId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComments", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlobName")
                        .IsUnique();

                    b.HasIndex("TaskCommentId");

                    b.ToTable("TaskCommentAttachments", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentMention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MentionedUserId")
                        .HasColumnType("int");

                    b.Property<int>("TaskCommentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MentionedUserId");

                    b.HasIndex("TaskCommentId", "MentionedUserId")
                        .IsUnique();

                    b.ToTable("TaskCommentMentions", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Contributor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EntraObjectId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Activity", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Activities")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ActivityMention", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Activity", "Activity")
                        .WithMany("Mentions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "MentionedUser")
                        .WithMany("ActivityMentions")
                        .HasForeignKey("MentionedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("MentionedUser");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Contribution", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Contributions")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "SubmittedByUser")
                        .WithMany("SubmittedContributions")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionAiPractice", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithOne("AiPractice")
                        .HasForeignKey("TeamIntelligenceHub.Domain.Entities.ContributionAiPractice", "ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionAttachment", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithMany("Attachments")
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionContributor", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithMany("Contributors")
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("ContributionCredits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contribution");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionCustomerStory", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithOne("CustomerStory")
                        .HasForeignKey("TeamIntelligenceHub.Domain.Entities.ContributionCustomerStory", "ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionLink", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithMany("Links")
                        .HasForeignKey("ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionMetric", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithOne("Metric")
                        .HasForeignKey("TeamIntelligenceHub.Domain.Entities.ContributionMetric", "ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionRisk", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithOne("Risk")
                        .HasForeignKey("TeamIntelligenceHub.Domain.Entities.ContributionRisk", "ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "OwnerUser")
                        .WithMany("OwnedContributionRisks")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Contribution");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.ContributionTestimonial", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Contribution", "Contribution")
                        .WithOne("Testimonial")
                        .HasForeignKey("TeamIntelligenceHub.Domain.Entities.ContributionTestimonial", "ContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribution");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.DocumentTestimonialAndCustomerStory", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.ContributionAttachment", "ContributionAttachment")
                        .WithMany()
                        .HasForeignKey("ContributionAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContributionAttachment");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Initiative", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "ExecutiveSponsor")
                        .WithMany("SponsoredInitiatives")
                        .HasForeignKey("ExecutiveSponsorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "Owner")
                        .WithMany("OwnedInitiatives")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExecutiveSponsor");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeMember", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Members")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("InitiativeMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeTask", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "AssignedToUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Tasks")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.Activity", "SourceActivity")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("SourceActivityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Initiative");

                    b.Navigation("SourceActivity");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskComment", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.TaskComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.InitiativeTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "User")
                        .WithMany("TaskComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentAttachment", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.TaskComment", "TaskComment")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskCommentMention", b =>
                {
                    b.HasOne("TeamIntelligenceHub.Domain.Entities.User", "MentionedUser")
                        .WithMany("TaskCommentMentions")
                        .HasForeignKey("MentionedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamIntelligenceHub.Domain.Entities.TaskComment", "TaskComment")
                        .WithMany("Mentions")
                        .HasForeignKey("TaskCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MentionedUser");

                    b.Navigation("TaskComment");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Activity", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("Mentions");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Contribution", b =>
                {
                    b.Navigation("AiPractice");

                    b.Navigation("Attachments");

                    b.Navigation("Contributors");

                    b.Navigation("CustomerStory");

                    b.Navigation("Links");

                    b.Navigation("Metric");

                    b.Navigation("Risk");

                    b.Navigation("Testimonial");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Contributions");

                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.InitiativeTask", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.TaskComment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Mentions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TeamIntelligenceHub.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ActivityMentions");

                    b.Navigation("AssignedTasks");

                    b.Navigation("ContributionCredits");

                    b.Navigation("CreatedTasks");

                    b.Navigation("InitiativeMemberships");

                    b.Navigation("OwnedContributionRisks");

                    b.Navigation("OwnedInitiatives");

                    b.Navigation("SponsoredInitiatives");

                    b.Navigation("SubmittedContributions");

                    b.Navigation("TaskCommentMentions");

                    b.Navigation("TaskComments");
                });
#pragma warning restore 612, 618
        }
    }
}
